name: "Enforce trusted commit signatures"

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  review:
    name: Validate Signatures
      runs-on: ubuntu-latest
      steps:
        - name: Fail
          run: exit 1
